require: rubocop-rspec

Layout/LineLength:
  Max: 130

AllCops:
  TargetRubyVersion: 3.0

Style/RedundantSelf:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "spec/*/**/*_spec.rb"

RSpec/DescribedClass:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    'ATCLite': 'ATC_lite'

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'define', 'shared_examples', 'factory']
