# Class to represents a location on the earth using latitude and longitude.
class Coordinate
  attr_reader latitude: Float

  attr_reader longitude: Float

  def initialize: (latitude: Numeric|String latitude, longitude: Numeric|String longitude) -> void

  def latitude=: (Numeric|String val) -> Float

  def longitude=: (Numeric|String val) -> Float

  def valid?: () -> bool

  def distance_to: (Coordinate final_coordinate) -> Float

  def initial_heading_to: (Coordinate final_coordinate) -> Float

  def final_heading_from: (Coordinate start_coordinate) -> Float

  def new_position: (heading: Numeric heading, distance: Numeric distance) -> Coordinate

  private

  def find_or_calc_vincenty_solution: (Coordinate final_coordinate) -> untyped

  def convert_degree_input_to_decimal: (untyped input, untyped valid_directions, untyped negative_direction) -> (nil | untyped)
end
