# Implements great circle calculations.  Thanks to http://www.movable-type.co.uk/scripts/latlong-vincenty.html
module LatLongCalcs
  EARTHS_RADIUS: Integer

  WGS84_F: Float

  def to_radians: (Numeric degrees) -> Float

  def to_degrees: (Numeric rads) -> Float

  def get_trig_trio: (Numeric rads) -> [Float, Float, Float]
end
